import { MenuItem, Reward, Transaction, TierInfo, User, PaymentMethod, UserRedemption } from '@/types';

export const TIER_INFO: Record<string, TierInfo> = {
  bronze: {
    level: 'bronze',
    name: 'Bronze Bean',
    minPoints: 0,
    maxPoints: 499,
    multiplier: 1,
    perks: ['Earn 1 point per $1', 'Birthday reward', 'Free refills'],
    color: '#cd7f32',
    icon: 'cafe-outline',
  },
  silver: {
    level: 'silver',
    name: 'Silver Sipper',
    minPoints: 500,
    maxPoints: 1499,
    multiplier: 1.5,
    perks: ['Earn 1.5x points', 'Early access to new drinks', 'Monthly bonus'],
    color: '#c0c0c0',
    icon: 'cafe',
  },
  gold: {
    level: 'gold',
    name: 'Gold Grinder',
    minPoints: 1500,
    maxPoints: 4999,
    multiplier: 2,
    perks: ['Earn 2x points', 'Free size upgrades', 'Exclusive rewards'],
    color: '#ffd700',
    icon: 'star',
  },
  platinum: {
    level: 'platinum',
    name: 'Platinum Barista',
    minPoints: 5000,
    maxPoints: 999999,
    multiplier: 3,
    perks: ['Earn 3x points', 'VIP events', 'Personalized drinks', 'Concierge service'],
    color: '#e5e4e2',
    icon: 'diamond',
  },
};

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Caramel Cloud Latte',
    description: 'Espresso with velvety oat milk foam and salted caramel drizzle',
    price: 5.95,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400',
    available: true,
    calories: 250,
    popular: true,
    customizations: [
      {
        id: 'size',
        name: 'Size',
        required: true,
        maxSelections: 1,
        options: [
          { id: 'small', name: 'Small (12oz)', priceModifier: 0 },
          { id: 'medium', name: 'Medium (16oz)', priceModifier: 0.80 },
          { id: 'large', name: 'Large (20oz)', priceModifier: 1.30 },
        ],
      },
      {
        id: 'milk',
        name: 'Milk',
        required: true,
        maxSelections: 1,
        options: [
          { id: 'oat', name: 'Oat Milk', priceModifier: 0 },
          { id: 'almond', name: 'Almond Milk', priceModifier: 0 },
          { id: 'whole', name: 'Whole Milk', priceModifier: 0 },
          { id: 'coconut', name: 'Coconut Milk', priceModifier: 0.50 },
        ],
      },
      {
        id: 'extras',
        name: 'Extras',
        required: false,
        maxSelections: 3,
        options: [
          { id: 'shot', name: 'Extra Shot', priceModifier: 0.75 },
          { id: 'vanilla', name: 'Vanilla Syrup', priceModifier: 0.50 },
          { id: 'whip', name: 'Whipped Cream', priceModifier: 0.50 },
        ],
      },
    ],
  },
  {
    id: '2',
    name: 'Rose Matcha Latte',
    description: 'Premium Japanese matcha with rose essence and creamy foam',
    price: 6.45,
    category: 'tea',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=400',
    available: true,
    calories: 180,
    popular: true,
    customizations: [
      {
        id: 'size',
        name: 'Size',
        required: true,
        maxSelections: 1,
        options: [
          { id: 'small', name: 'Small (12oz)', priceModifier: 0 },
          { id: 'medium', name: 'Medium (16oz)', priceModifier: 0.80 },
          { id: 'large', name: 'Large (20oz)', priceModifier: 1.30 },
        ],
      },
    ],
  },
  {
    id: '3',
    name: 'Classic Americano',
    description: 'Rich espresso with hot water, simple and bold',
    price: 3.95,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400',
    available: true,
    calories: 15,
    customizations: [
      {
        id: 'size',
        name: 'Size',
        required: true,
        maxSelections: 1,
        options: [
          { id: 'small', name: 'Small (12oz)', priceModifier: 0 },
          { id: 'medium', name: 'Medium (16oz)', priceModifier: 0.50 },
          { id: 'large', name: 'Large (20oz)', priceModifier: 1.00 },
        ],
      },
    ],
  },
  {
    id: '4',
    name: 'Butter Croissant',
    description: 'Flaky, golden French croissant with pure butter',
    price: 4.25,
    category: 'pastry',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400',
    available: true,
    calories: 340,
    popular: true,
  },
  {
    id: '5',
    name: 'Avocado Toast',
    description: 'Smashed avocado on sourdough with cherry tomatoes and microgreens',
    price: 8.95,
    category: 'sandwich',
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
    available: true,
    calories: 420,
  },
  {
    id: '6',
    name: 'Mango Passion Smoothie',
    description: 'Tropical blend of mango, passion fruit, and coconut cream',
    price: 6.95,
    category: 'smoothie',
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
    available: true,
    calories: 290,
    popular: true,
  },
  {
    id: '7',
    name: 'Iced Vanilla Cold Brew',
    description: '20-hour cold brew with Madagascar vanilla and cream',
    price: 5.45,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400',
    available: true,
    calories: 120,
  },
  {
    id: '8',
    name: 'Blueberry Muffin',
    description: 'Fresh-baked muffin bursting with organic blueberries',
    price: 3.75,
    category: 'pastry',
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=400',
    available: true,
    calories: 380,
  },
  {
    id: '9',
    name: 'Pumpkin Spice Latte',
    description: 'Seasonal favorite with real pumpkin, warm spices, and foam',
    price: 6.25,
    category: 'seasonal',
    image: 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=400',
    available: true,
    calories: 310,
    popular: true,
  },
  {
    id: '10',
    name: 'Turkey Club Sandwich',
    description: 'Roasted turkey, bacon, avocado on toasted ciabatta',
    price: 11.95,
    category: 'sandwich',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400',
    available: true,
    calories: 580,
  },
];

export const REWARDS: Reward[] = [
  {
    id: '1',
    name: 'Free Any Size Coffee',
    pointsRequired: 150,
    description: 'Redeem for any hot or iced coffee, any size',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    category: 'drink',
    active: true,
    expiryDays: 30,
  },
  {
    id: '2',
    name: 'Free Pastry',
    pointsRequired: 100,
    description: 'Choose any pastry from our bakery case',
    image: 'https://images.unsplash.com/photo-1558326567-98ae2405596b?w=400',
    category: 'food',
    active: true,
    expiryDays: 14,
  },
  {
    id: '3',
    name: 'Free Specialty Drink',
    pointsRequired: 250,
    description: 'Any handcrafted specialty beverage on us',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400',
    category: 'drink',
    active: true,
    expiryDays: 30,
  },
  {
    id: '4',
    name: 'BrewRewards Mug',
    pointsRequired: 500,
    description: 'Exclusive ceramic mug with 10% off refills forever',
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400',
    category: 'merchandise',
    active: true,
    expiryDays: 90,
  },
  {
    id: '5',
    name: 'Barista Experience',
    pointsRequired: 1000,
    description: 'Private 1-hour session learning latte art from our baristas',
    image: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=400',
    category: 'experience',
    active: true,
    expiryDays: 60,
  },
  {
    id: '6',
    name: 'Free Breakfast Combo',
    pointsRequired: 300,
    description: 'Any sandwich + any drink combo',
    image: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=400',
    category: 'food',
    active: true,
    expiryDays: 21,
  },
];

export const MOCK_USER: User = {
  id: 'user-001',
  phone: '+1 (555) 123-4567',
  email: 'emma.wilson@email.com',
  name: 'Emma Wilson',
  avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
  createdAt: new Date('2024-01-15'),
  totalPointsEarned: 2847,
  currentPoints: 1235,
  tierLevel: 'gold',
};

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn-001',
    userId: 'user-001',
    amount: 12.40,
    pointsEarned: 25,
    pointsRedeemed: 0,
    items: [
      { menuItem: MENU_ITEMS[0], quantity: 1, customizations: [], subtotal: 5.95 },
      { menuItem: MENU_ITEMS[3], quantity: 1, customizations: [], subtotal: 4.25 },
    ],
    timestamp: new Date('2025-01-15T08:32:00'),
    receiptUrl: 'receipt-001',
    status: 'completed',
    storeName: 'BrewRewards Downtown',
  },
  {
    id: 'txn-002',
    userId: 'user-001',
    amount: 6.45,
    pointsEarned: 13,
    pointsRedeemed: 0,
    items: [
      { menuItem: MENU_ITEMS[1], quantity: 1, customizations: [], subtotal: 6.45 },
    ],
    timestamp: new Date('2025-01-14T14:15:00'),
    receiptUrl: 'receipt-002',
    status: 'completed',
    storeName: 'BrewRewards Midtown',
  },
  {
    id: 'txn-003',
    userId: 'user-001',
    amount: 0,
    pointsEarned: 0,
    pointsRedeemed: 150,
    items: [
      { menuItem: MENU_ITEMS[2], quantity: 1, customizations: [], subtotal: 0 },
    ],
    timestamp: new Date('2025-01-12T09:45:00'),
    receiptUrl: 'receipt-003',
    status: 'completed',
    storeName: 'BrewRewards Union Square',
  },
  {
    id: 'txn-004',
    userId: 'user-001',
    amount: 19.85,
    pointsEarned: 40,
    pointsRedeemed: 0,
    items: [
      { menuItem: MENU_ITEMS[4], quantity: 1, customizations: [], subtotal: 8.95 },
      { menuItem: MENU_ITEMS[5], quantity: 1, customizations: [], subtotal: 6.95 },
    ],
    timestamp: new Date('2025-01-10T12:30:00'),
    receiptUrl: 'receipt-004',
    status: 'completed',
    storeName: 'BrewRewards Downtown',
  },
  {
    id: 'txn-005',
    userId: 'user-001',
    amount: 5.45,
    pointsEarned: 11,
    pointsRedeemed: 0,
    items: [
      { menuItem: MENU_ITEMS[6], quantity: 1, customizations: [], subtotal: 5.45 },
    ],
    timestamp: new Date('2025-01-08T16:20:00'),
    receiptUrl: 'receipt-005',
    status: 'completed',
    storeName: 'BrewRewards Brooklyn',
  },
];

export const MOCK_PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: 'pm-001',
    userId: 'user-001',
    type: 'visa',
    last4Digits: '4242',
    cardHolder: 'Emma Wilson',
    expiryDate: '12/26',
    isDefault: true,
  },
  {
    id: 'pm-002',
    userId: 'user-001',
    type: 'apple_pay',
    last4Digits: '8888',
    cardHolder: 'Emma Wilson',
    expiryDate: '',
    isDefault: false,
  },
];

export const MOCK_REDEMPTIONS: UserRedemption[] = [
  {
    id: 'red-001',
    userId: 'user-001',
    reward: REWARDS[0],
    redeemedAt: new Date('2025-01-05'),
    expiryDate: new Date('2025-02-05'),
    status: 'active',
    code: 'BREW-7X9K2M',
  },
  {
    id: 'red-002',
    userId: 'user-001',
    reward: REWARDS[1],
    redeemedAt: new Date('2024-12-20'),
    expiryDate: new Date('2025-01-03'),
    status: 'used',
    code: 'BREW-3P5N8Q',
  },
];

export const MENU_CATEGORIES = [
  { id: 'all', name: 'All', icon: 'grid-outline' },
  { id: 'coffee', name: 'Coffee', icon: 'cafe-outline' },
  { id: 'tea', name: 'Tea', icon: 'leaf-outline' },
  { id: 'pastry', name: 'Pastry', icon: 'pizza-outline' },
  { id: 'sandwich', name: 'Food', icon: 'fast-food-outline' },
  { id: 'smoothie', name: 'Smoothie', icon: 'water-outline' },
  { id: 'seasonal', name: 'Seasonal', icon: 'sparkles-outline' },
];